name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

env:
  AZURE_WEBAPP_NAME_API: ai-chatbot-api-t7xmwp
  AZURE_WEBAPP_NAME_UI: ai-chatbot-ui-t7xmwp

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-build
          path: Backend.Api

      - name: Update appsettings
        uses: microsoft/variable-substitution@v1
        with:
          files: Backend.Api/appsettings.json
        env:
          AzureOpenAI.Endpoint: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AzureOpenAI.ApiKey: ${{ secrets.AZURE_OPENAI_APIKEY }}
          AzureOpenAI.DeploymentName: ${{ secrets.AZURE_OPENAI_DEPLOYMENTNAME }}
          AzureAd.TenantId: ${{ secrets.AZURE_AD_TENANT_ID }}
          AzureAd.ClientId: ${{ secrets.AZURE_AD_CLIENT_ID }}
          AzureAd.ClientSecret: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          AzureAd.Audiences__0: ${{ secrets.AZURE_AD_AUDIENCES_0 }}
          AzureAd.Audiences__1: ${{ secrets.AZURE_AD_AUDIENCES_1 }}
          SwaggerUI.ClientId: ${{ secrets.AZURE_AD_CLIENT_ID }}
          SwaggerUI.Scope: ${{ secrets.SWAGGER_UI_SCOPE}}

      - name: Deploy to Azure Web App (API)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_API }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
          package: Backend.Api

  deploy-ui:
    runs-on: ubuntu-latest
    needs: deploy-api
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: Frontend.Web

      - name: Deploy to Azure Web App (UI)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_UI }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_UI }}
          package: Frontend.Web